platform :ios, '9.0'

target 'TestWithFlutter' do
  
  pod 'IQKeyboardManagerSwift', '~> 6.5.4'
  
  flutter_application_path = '../flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)
end
